spring.jackson.default-property-inclusion: non_null
logging:
  level.root: WARN
  level.no.ccat: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
management:
  server:
    port: 8181

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
  searchApiUrl: http://localhost:8083
  registrationApiUrl: https://localhost:8099
elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8088
management:
  server:
    port: 8997
