spring:
  jackson:
    default-property-inclusion: non_null
  data:
    elasticsearch:
      clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
      clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}

logging:
  level.root: WARN
  level.no.fdk.imcat: DEBUG
  level.no.fdk.imcat.service: DEBUG
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.springframework.data.elasticsearch: ${LOG_LEVEL:INFO}
application:
  apiRootUrl: http://nginx-search:8080/api
  harvestSourceUri: https://fellesdatakatalog.brreg.no/api
  # harvest every sixth hour, 10 minutes after apicatalogs update
  harvestCron: 0 10 */6 * * *


---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
  data:
    elasticsearch:
      clusterNodes: localhost:9300
      clusterName: elasticsearch
application:
  apiRootUrl: http://localhost:8080/api
server:
  port: 8090
