logging:
  level.: ERROR
  level.no.brreg: INFO
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
spring:
  mvc.view.prefix: /WEB-INF/jsp/
  mvc.view.suffix: .jsp
server:
  port: 8080
management:
  port: 8181
fuseki:
  dcatServiceUri: http://fuseki:8080/fuseki/dcat
  adminServiceUri: http://fuseki:8080/fuseki/admin
application:
  harvesterUrl: http://harvester-api:8080
  kibanaLinkFirstHalf: "/app/kibana/#/dashboard/dashboard_template?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:4,id:DCATCrawler-Operations,panelIndex:1,row:3,size_x:9,size_y:3,type:visualization),(col:1,id:DCATCrawler-Results,panelIndex:2,row:3,size_x:3,size_y:3,type:visualization),(col:1,id:DCATCrawler-Metadata,panelIndex:4,row:1,size_x:12,size_y:2,type:visualization),(col:7,id:Validation-RuleId,panelIndex:6,row:6,size_x:6,size_y:4,type:visualization),(col:1,columns:!(ruleSeverity,event,cause,ruleId),id:validation_ruleId,panelIndex:7,row:6,size_x:6,size_y:4,sort:!(timestamp,desc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'%22"
  kibanaLinkSecondHalf: "%22')),title:dashboard_template,uiState:())"
  adminUsername: ${harvester_adminUsername}
  adminPassword: ${harvester_adminPassword}

---

spring:
  profiles: develop
logging:
  level.: ERROR
  level.no.brreg: INFO
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: DEBUG
  level.org.springframework.web: DEBUG
fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin
application:
  harvesterUrl: http://localhost:8081
server:
  port: 8082
management:
  port: 8992