spring.jackson.default-property-inclusion: non_null
logging:
  level.: WARN
  level.no.acat: INFO
  level.org.springframework: WARN
  level.org.springframework.web: WARN
application:
  searchApiUrl: http://search-api:8080
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
server:
  port: 8080
management:
  server:
    port: 8181

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
  referenceDataUrl: http://localhost:8100
  searchApiUrl: http://localhost:8083
elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8088
management:
  server:
    port: 8997
