spring:
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
logging:
  level.root: WARN
  level.no.acat: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
application:
  apiRootUrl: http://nginx-search:8080/api
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
server:
  port: 8080
management:
  server:
    port: 8181

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
  apiRootUrl: http://localhost:8080/api
elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8088
management:
  server:
    port: 8997
