logging:
  level.: ERROR
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
application:
  fusekiService: http://fuseki:8080/fuseki
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
server:
  port: 8080
management:
  server:
    port: 8181

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
  fusekiService: http://localhost:3030/fuseki
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
logging:
  level.: ERROR
  level.no.brreg: INFO
  level.org.springframework: ERROR
server:
  port: 8083
management:
  server:
    port: 8993
