logging:
  level.root: ERROR
  level.no.brreg: ERROR
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/ld+json
    tomcat:
        compression: on
application:
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}

---

spring:
  profiles: develop
server:
  port: 8100
management:
  server:
    port: 8101


