logging:
  level.root: ERROR
  level.no.brreg: ERROR
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: ERROR
server:
  port: 8080
management:
  server:
    port: 8181

---
spring:
  profiles: develop
server:
  port:8077
  