spring:
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
management:
  endpoints.web.exposure.include: health, readiness
application:
  altinnProxyHost: ${ALTINN_PROXY_HOST:http://nginx-altinn-proxy:8080}
  # 920210023   /* this matches in prod system "GJELDSREGISTERET AS”*/
  # 910258028   /* this matches in mock data "LILAND OG ERDAL REVISJON", used in dev, ut1, st1 and it1*/
  orgNrWhitelist: ${ORGNR_WHITELIST:920210023,910258028}
  orgFormWhitelist: ${ORGFORM_WHITELIST:ADOS,FKF,FYLK,IKS,KF,KIRK,KOMM,ORGL,SF,STAT,SÆR}
  adminList: ${ADMIN_LIST:23076102252} #MAUD GULLIKSEN

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
#  altinnProxyHost: http://localhost:8126 # the actual proxy, requieres cert configuration
  altinnProxyHost: http://localhost:8128 #mock
server:
  port: 8125
