logging:
  level.root: ERROR
  level.no: ${LOG_LEVEL:INFO}
  level.org.springframework: INFO
  level.org.springframework.web: ERROR
  level.org.springframework.data.elasticsearch.core: ${LOG_LEVEL:INFO}
  level.org.opensaml: INFO
application:
  themesServiceUrl: http://reference-data:8080
  catalogUriPrefix: http://localhost:8099
  apikey: ${registrationApi_apikey:12345-ABCDE-67890-FGHIJ}
  altinnServiceUrl: ${registrationApi_altinnServiceUrl:http://registration-auth:8080}
  altinnServiceCode: ${registrationApi_altinnServiceCode:4814}
  altinnServiceEdition: ${registrationApi_altinnServiceEdition:3}
  clientSSLCertificateKeystoreLocation: ${registrationApi_clientSSLCertificateKeystoreLocation:conf/dummy-client-SSL-cert.p12}
  clientSSLCertificateKeystorePassword: ${registrationApi_clientSSLCertificateKeystorePassword:password}
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}
  harvesterUsername: ${registrationApi_harvesterUsername:test_admin}
  harvesterPassword: ${registrationApi_harvesterPassword:password}
  harvesterUrl: http://harvester:8080
  openDataEnhet: ${FDK_ENHETSREGISTERET_URL:https://data.brreg.no/enhetsregisteret/api/enheter/}
  openDataEnhetProxy: ${FDK_ENHETSREGISTERET_PROXY_URL:http://nginx-enhetsregisteret-proxy:8080/enhetsregisteret/api/enheter/}
  apiRootUrl: http://nginx-search:8080/api
  # harvest every sixth hour
  harvestCron: 0 0 */6 * * *
  authentication:
    includedOrgforms: ADOS,FKF,FYLK,IKS,KF,KIRK,KOMM,ORGL,SF,STAT,SÃ†R
    includedOrgnr: 974760673,920210023,938275130


spring:
  jackson:
    default-property-inclusion: non_null
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    elasticsearch:
      clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
      clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}

saml:
  sso:
    metadata-generator:
      entity-id: difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}
    idp:
      metadata-location: file:${registrationApi_idportenMetadataFile:conf/idporten/idporten-ver2.difi.no-v3_signed_meta.xml}
      localMetadataLocation: file:conf/idporten/difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}.xml
    metadata-manager:
      refresh-check-interval: -1
    key-manager:
      public-key-pem-location: file:conf/idporten/difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}.xml
      store-location: file:conf/idporten/difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}.jks
      store-pass: ${registrationApi_ipStorePassword}
      default-key: difi.brreg.datakatalog.registrering.${registrationApi_OpenshiftEnvironment:dev}
      key-passwords:
        difi.brreg.datakatalog.registrering.it1: ${registrationApi_ipKeyPassword}
        difi.brreg.datakatalog.registrering.st1: ${registrationApi_ipKeyPassword}
        difi.brreg.datakatalog.registrering.ppe: ${registrationApi_ipKeyPassword}
        difi.brreg.datakatalog.registrering.prd: ${registrationApi_ipKeyPassword}
        difi.brreg.datakatalog.registrering.tt1: ${registrationApi_ipKeyPassword}
        difi.brreg.datakatalog.registrering.ut1: ${registrationApi_ipKeyPassword}
        difi.brreg.datakatalog.registrering.st2: ${registrationApi_ipKeyPassword}
        difi.brreg.datakatalog.registrering.dev: ${registrationApi_ipKeyPassword}
    context-provider:
      lb:
        context-path: /
        include-server-port-in-request-url: ${registrationApi_IncludeServerPortInRequestUrl:true}
        scheme: https
        server-name: ${registrationApi_ServerName:localhost}
        server-port: ${registrationApi_ServerPort:8099}
    logout:
      default-target-url: /

server:
  tomcat:
    accesslog:
      enabled: true
    basedir: /tmp/fdk

---
spring:
  profiles: develop
  data:
    elasticsearch:
      clusterNodes: localhost:9300
      clusterName: elasticsearch
server:
  port: 8115
  ssl:
    key-store: conf/idporten/ssldevelop.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: tomcat
application:
  harvesterUrl: http://localhost:8082
  altinnServiceUrl: http://localhost:8077
  apiRootUrl: http://localhost:8080/api

---
spring:
  profiles: unit-integration
  data:
    elasticsearch:
      clusterNodes: localhost:9399
      clusterName: elasticsearch
      properties:
        http:
          enabled: true
application:
  themesServiceUrl: http://localhost:8100
  clientSSLCertificateKeystoreLocation: ../../conf/dummy-client-SSL-cert.p12
  clientSSLCertificateKeystorePassword: password
  altinnServiceUrl: http://localhost:8077
  altinnServiceCode: 1234
  altinnServiceEdition: 42
  apiKey: 1234-abcde-56789-fghij
  harvesterUrl: http://localhost:8082

